### ISSUE TITLE
Restricting ROIs for analysis

### ISSUE THREAD

**Issue by egleich** [neurolabusc/NiiStat#1]
Would it be possible to restrict the analyses to specific ROIs, entered manually?

**Comment by neurolabusc** [comment]
Zeke-

  Please try out the 29 March 2015 release there are two ways to do this:
1.) Graphical interface method:
 a.) run nii_stat and select your Excel file.
 b.) in the 'Options' dialog window enter '5' in the 'Special' box to request a custom ROI.
 c.) wait for the software to load your data
 d.) a new dialog box appears allowing you to restrict your ROIs. For example if you include 1,2, 6 then only the first, second and sixth regions will be analyzed.

2.) Global method 
 a.) from the Matlab command line specify
       global roiMask
       roiMask = [1 2 5]
 b.) run nii_stat from the command line, select your Excel file and run as normally.
 c.) In this example only the 1st, 2nd and 5th region will be analyzed.
 d.) WARNING: this inclusion criteria will remain until you either quit matlab or change the criteria. For example, to turn off the mask you need to type the following in the Matlab command line
      roiMask = [];
 e.) Hint, you can specify ranges easily with this method:
     roiMask = [1:4 88:92]

 Note: by default Nii_Stat excludes regions that are white matter or CSF from the connectivity analyses. Therefore, the JHU atlas that has 189 regions will only analyze 110 regions, hence you get the message
   Connectivity only analyzing gray matter regions (110 of 189)
If you want to remove this exclusion criteria please enter '4' in the specials option ("include WM/CSF in connectivity analyses").
