### ISSUE TITLE
GUI and script not working

### ISSUE THREAD

**Issue by sosinovitch** [neurolabusc/NiiStat#7]
I just tried running the NiiStat and NiiStatGUI scripts via MATLAB (2018b) on my iMac, and get the following error message for the NiiStat script:

_Error using NiiStat (line 85)
Unable to find Excel file named
/home/research/Desktop/PACMAN_MASTER/MRI_Data/PacManNiiStat_Paper_3.xlsx_

Here's line 85 of the code:

`
if (strcmpi('ver',xlsname)), return; end;
 %nii_stat('ver') cause software to report version and quit
if exist(xlsname,'file') ~= 2
    error('Unable to find Excel file named %s\n',xlsname);
end`

It looks like the script is looking for an Excel file, and halts the script once the PacManNiiStat_Paper_3.xlsx Excel file isn't found. 

For the GUI, here's a screenshot of a subset of the error messages that pop up:
<img width="1190" alt="Screen Shot 2019-05-01 at 7 07 05 PM" src="https://user-images.githubusercontent.com/50184967/57048996-5c158180-6c44-11e9-8160-7c21b840579c.png">

The GUI itself appears blank with the following tabs:

<img width="752" alt="Screen Shot 2019-05-01 at 7 08 38 PM" src="https://user-images.githubusercontent.com/50184967/57049045-89622f80-6c44-11e9-8938-127242f5e4a8.png">

Any help fixing these bugs would be greatly appreciated.

**Comment by rogiedodgie** [comment]
Did you type NiiStat at the prompt or NiiStatGUI at the Matlab prompt?
With the current release you must start the program using the NiiStatGUI command. You will then have the option to use the classic interface once it starts.
Roger

**Comment by sosinovitch** [comment]
Yes, tried that. **The problem was solved by removing all the spm12 subfolders from the Set Path area.** 

Got a warning from spm12 that all that was required was the main folder, so removed all spm12 subfolders and only included the main folder in the Set Path. After removing doing this, when I entered the NiiStatGUI command, the GUI started perfectly.

**Comment by Manuel-debugger** [comment]
I'm having this exact issue. Tried the suggested solution of removing all the spm12 subfolders from the path but nothing.

Error:
Error using NiiStat (line 85)
Unable to find Excel file named /home/research/Desktop/PACMAN_MASTER/MRI_Data/PacManNiiStat_Paper_3.xlsx

**Comment by rogiedodgie** [comment]
Please type NiiStatGUI, not NiiStat, at the Matlab prompt.
-R

**Comment by sosinovitch** [comment]
Just installed NiiStat on a Mac with macOS Mojave, and typing NiiStatGUI got the GUI interface to pop up whereas NiiStat gave the aforementioned error. I didn't have to change anything. Thanks for the tip @rogiedodgie.
